name: Daily LinkedIn Post
on:
  schedule:
    - cron: '51 16 * * *'  # 9 AM daily (UTC)
  workflow_dispatch:  # Allow manual runs
jobs:
  generate-post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run Script
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
        run: main.py
