name: Daily LinkedIn Post
on:
  schedule:
    - cron: '15 11 * * *'  # 4:45 PM IST
  workflow_dispatch:

jobs:
  generate-post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 🔽 Add this new step HERE 🔽
      - name: Clean install dependencies
        run: |
          pip uninstall -y openai pydantic-core
          pip install --force-reinstall -r requirements.txt

      - name: Install dependencies  # Existing step
        run: pip install -r requirements.txt

      - name: Run Script
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
        run: python linkedin_automation.py
